(function() {
  const { useRef, useEffect, useState } = React;

  window.VolumeForecast = function({ forecast }) {
    const chartRef = useRef(null);
    const chartInstance = useRef(null);
    const [showSql, setShowSql] = useState(false);

    useEffect(() => {
      if (!chartRef.current) return;

      if (chartInstance.current) {
        chartInstance.current.destroy();
      }

      const historical = Object.entries(forecast.historical_monthly).map(([month, val]) => ({
        x: month.slice(5),
        y: val,
        forecast: false
      }));
      
      const lastHist = historical[historical.length - 1];

      const fc = Object.entries(forecast.forecast_months).map(([month, val]) => ({
        x: month.slice(5) + "*",
        y: val,
        forecast: true
      }));

      const actualSeriesData = [...historical];
      const forecastSeriesData = Array(historical.length - 1).fill(null);
      forecastSeriesData.push({ x: lastHist.x, y: lastHist.y });
      fc.forEach(f => forecastSeriesData.push(f));

      const categories = [...historical.map(h => h.x), ...fc.map(f => f.x)];

      const options = {
        series: [{
          name: 'Actual Ticket Volume',
          data: actualSeriesData.map(d => d.y)
        }, {
          name: 'Forecasted Volume',
          data: forecastSeriesData.map(d => d ? d.y : null)
        }],
        chart: {
          type: 'line',
          height: 250,
          toolbar: { show: false }
        },
        colors: ['#16233D', '#B4432F'],
        stroke: {
          width: [3, 3],
          curve: 'smooth',
          dashArray: [0, 5]
        },
        markers: {
          size: [3, 4],
          colors: ['#16233D', '#B4432F'],
          strokeWidth: 0,
        },
        xaxis: {
          categories: categories,
          labels: { style: { fontSize: '10px' } }
        },
        yaxis: {
          labels: { style: { fontSize: '10px' } }
        },
        grid: {
          borderColor: '#DCD5C6',
          strokeDasharray: 3,
        },
        tooltip: {
          y: { formatter: (v) => `${v} tickets` }
        },
        legend: {
          fontSize: '10px',
          position: 'top',
          horizontalAlign: 'right'
        }
      };

      chartInstance.current = new ApexCharts(chartRef.current, options);
      chartInstance.current.render();

      return () => {
        if (chartInstance.current) {
          chartInstance.current.destroy();
        }
      };
    }, [forecast]);

    return html`
      <section class="bg-white border border-[#DCD5C6] rounded-lg p-5 shadow-sm">
        <div class="flex flex-wrap items-center justify-between gap-4 mb-4">
          <div class="flex items-center gap-3">
            <span class="text-xs tracking-widest font-semibold text-[#B4432F]">TRENDING</span>
            <h2 class="text-lg font-bold text-[#16233D] serif-font">Ticket Volume Forecast (2025 Actuals vs Q1 2026 Forecast)</h2>
          </div>
          <button onClick=${() => setShowSql(!showSql)} class="text-xs font-semibold px-2.5 py-1.5 border border-[#DCD5C6] rounded bg-[#F6F3EC] hover:bg-[#eae6db] text-stone-600 transition-colors">
            ${showSql ? 'Hide SQL Query' : 'View SQL Query'}
          </button>
        </div>

        <!-- SQL DRAWER -->
        ${showSql && html`
          <div class="mb-4 p-3 bg-stone-900 text-[#eae6db] rounded-md overflow-x-auto text-xs mono-font">
            <span class="text-[#888] block mb-1">-- Ticket volume monthly aggregates (used to train forecast)</span>
            <pre>SELECT
    DATE_TRUNC('month', created_at) AS month,
    COUNT(*) AS ticket_count
FROM fact_tickets
GROUP BY month
ORDER BY month;</pre>
          </div>
        `}

        <div class="border border-[#DCD5C6] rounded p-4 bg-[#FBFBFA]">
          <div ref=${chartRef} class="w-full h-64"></div>
          <div class="text-[10px] text-stone-500 mt-2 text-right">
            *Dotted line segments show Q1 2026 forecast generated by a linear trend + seasonality weights model.
          </div>
        </div>
      </section>
    `;
  };
})();
